import { test, expect } from '@playwright/test';
test('mobile canvas, bottom sheets, menu and full-page preview',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');
 await expect(page.locator('.workspace>.sidebar')).toBeHidden();
 await expect(page.locator('.canvas-toolbar')).toBeHidden();
 await expect(page.locator('.mobile-tools')).toBeVisible();
 await page.locator('[data-id="intro"]').click();
 await expect(page.locator('.mobile-sheet')).toBeVisible();await expect(page.locator('#card-title')).toHaveValue('Alex Morgan');
 await page.locator('#card-title').fill('Mobile creator');await page.locator('#card-title').press('Tab');
 await page.locator('.sheet-done').click();await expect(page.locator('.mobile-sheet')).toHaveCount(0);
 await expect(page.locator('[data-id="intro"] h2')).toHaveText('Mobile creator');
 await page.locator('[data-mobile-tool="blocks"]').click();await page.locator('[data-add="text"]').click();
 await expect(page.locator('.mobile-sheet')).toBeVisible();await expect(page.locator('#card-title')).toHaveValue('What’s on my mind');
 await page.keyboard.press('Escape');await page.locator('[data-mobile-tool="design"]').click();
 await expect(page.locator('.design-controls')).toBeVisible();await page.locator('.sheet-done').click();
 await page.locator('[data-mobile-tool="preview"]').click();await expect(page.locator('.mobile-tools')).toHaveCount(0);await expect(page.locator('.card[draggable]')).toHaveCount(0);
 await page.locator('#preview').click();await page.locator('.mobile-menu-toggle').click();await page.getByRole('button',{name:'Explore templates',exact:true}).click();
 await expect(page.locator('.template-dialog')).toBeVisible();await page.keyboard.press('Escape');
 await page.screenshot({path:'test-results/mobile-canvas.png'});
 await page.locator('[data-mobile-tool="design"]').click();await page.screenshot({path:'test-results/mobile-sheet.png'});
 await page.setViewportSize({width:1440,height:1000});await expect(page.locator('.workspace>.sidebar')).toBeVisible();await expect(page.locator('.mobile-sheet')).toHaveCount(0);
});
test('gallery batch upload, reorder, viewer and standalone export',async({page,context})=>{
 await page.goto('/');await page.locator('[data-tab="blocks"]').click();await page.locator('[data-add="gallery"]').click();
 const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=50;c.height=50;const ctx=c.getContext('2d');ctx.fillStyle='#ff5500';ctx.fillRect(0,0,50,50);return c.toDataURL('image/png').split(',')[1]});
 const embedded=await page.evaluate(async image=>{const {exportImages}=await import('/src/cloud.js');const result=await exportImages({cards:[{type:'gallery',images:[{image:'data:image/png;base64,'+image,imagePath:'test/photo.png'}]}]});return result.cards[0].images[0]},image);
 expect(embedded.image).toMatch(/^data:image\/png/);expect(embedded.imagePath).toBeUndefined();
 await page.locator('#gallery-upload').setInputFiles(['one','two'].map(name=>({name:name+'.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')})));
 await expect(page.locator('#gallery-status')).toContainText('Photos added');
 await page.locator('[data-caption="0"]').fill('First image');await page.locator('[data-caption="0"]').press('Tab');
 await page.locator('[data-image-move="0"][data-direction="1"]').click();
 await expect(page.locator('[data-caption="1"]')).toHaveValue('First image');
 await page.locator('#gallery-mode').selectOption('slider');await page.locator('#preview').click();
 await expect(page.locator('.gallery-position')).toHaveText('1 / 2');
 await expect(page.locator('[data-gallery-step="-1"]')).toBeDisabled();
 expect(await page.locator('.gallery-slider').evaluate(el=>getComputedStyle(el).scrollbarWidth)).toBe('none');
 await page.locator('[data-gallery-step="1"]').click();await expect(page.locator('.gallery-position')).toHaveText('2 / 2');await expect(page.locator('[data-gallery-step="1"]')).toBeDisabled();
 await page.locator('.gallery-slider').focus();await page.keyboard.press('Home');await expect(page.locator('.gallery-position')).toHaveText('1 / 2');
 await page.locator('[data-gallery-open="0"]').click();await expect(page.locator('.gallery-lightbox')).toBeVisible();
 await page.keyboard.press('ArrowRight');await expect(page.locator('.gallery-lightbox p')).toHaveText('First image');await page.keyboard.press('Escape');
 const pending=page.waitForEvent('download');await page.locator('#page-menu-toggle').click();await page.locator('#export').click();const file=await pending;const stream=await file.createReadStream();let html='';for await(const chunk of stream)html+=chunk;
 const exported=await context.newPage();await exported.setContent(html);await exported.locator('.gallery-slider').focus();await exported.keyboard.press('End');await expect(exported.locator('.gallery-position')).toHaveText('2 / 2');await exported.keyboard.press('Home');await exported.locator('[data-gallery-open="0"]').click();await expect(exported.locator('.gallery-lightbox')).toBeVisible();await exported.close();
 await page.reload();await expect(page.locator('.gallery-item')).toHaveCount(2);
});
test('photographer sample has a gallery and developer sample has projects',async({page})=>{
 await page.goto('/');await page.locator('#page-menu-toggle').click();await page.locator('#templates').click();await page.locator('[data-template="photographer"]').click();await page.locator('#keep-content').uncheck();await page.locator('#apply-template').click();
 await expect(page.locator('.page-nav strong')).toContainText('Luka Novak');await expect(page.locator('.gallery-item')).toHaveCount(3);
 await page.locator('#page-menu-toggle').click();await page.locator('#templates').click();await page.locator('[data-template="developer"]').click();await page.locator('#keep-content').uncheck();await page.locator('#apply-template').click();await expect(page.locator('.page-nav strong')).toContainText('Nika Kovač');await expect(page.locator('.card.project')).toHaveCount(1);
});
import {normalizeLink} from '../src/links.js';
test('link destinations normalize safely',()=>{
 expect(normalizeLink('github.com/example','github')).toBe('https://github.com/example');
 expect(normalizeLink('hello@example.com','email')).toBe('mailto:hello@example.com');
 expect(()=>normalizeLink('javascript:alert(1)','website')).toThrow();
 expect(()=>normalizeLink('not an email','email')).toThrow();
});
test('add social and email cards with working destinations',async({page})=>{
 await page.goto('/');await page.locator('#add-link').click();
 await page.locator('[data-link-kind="instagram"]').click();
 await page.locator('[name="destination"]').fill('instagram.com/verbaspark');
 await page.getByRole('button',{name:'Add to my page'}).click();
 await expect(page.locator('.bento .card')).toHaveCount(10);
 await expect(page.locator('.card.selected a')).toHaveAttribute('href','https://instagram.com/verbaspark');
 await page.locator('#add-link').click();await page.locator('[data-link-kind="email"]').click();
 await page.locator('[name="destination"]').fill('hello@verbaspark.com');
 await page.getByRole('button',{name:'Add to my page'}).click();
 await expect(page.locator('.card.selected a')).toHaveAttribute('href','mailto:hello@verbaspark.com');
 await page.locator('#preview').click();
 await expect(page.locator('a[href="mailto:hello@verbaspark.com"]')).toBeVisible();
 await page.reload();await expect(page.locator('.bento .card')).toHaveCount(11);
});
import {cleanPage} from '../src/page-data.js';
test('cloud document sanitization restricts styles and card markup',()=>{
 const page=cleanPage({name:'Example',cards:[{type:'bad" onclick="alert(1)',id:'bad',size:'bad',crop:{x:'" onerror="oops',zoom:9000}}],design:{headingFont:'bad',background:'red;position:fixed',weight:99999}});
 expect(page.cards[0].type).toBe('text');expect(page.cards[0].crop.x).toBe(50);expect(page.cards[0].crop.zoom).toBe(200);expect(page.design.background).toBe('#101318');expect(page.design.weight).toBe(700);
});
test('unconfigured cloud is explicit and does not pretend to publish',async({page})=>{
 await page.goto('/');await page.locator('#page-menu-toggle').click();await page.locator('#account').click();
 await expect(page.locator('.account-dialog')).toContainText('need a Supabase connection');
 await page.keyboard.press('Escape');await expect(page.locator('.account-dialog')).toHaveCount(0);
 await page.goto('/p/example');await expect(page.locator('#app')).toHaveText('Publishing is not connected yet.');
});
test('templates preview without changes, preserve content, replace optionally and undo',async({page})=>{
 await page.goto('/');await page.locator('#page-menu-toggle').click();await page.locator('#templates').click();
 await page.locator('[data-template="personal"]').click();
 await expect(page.frameLocator('iframe[title="Template preview"]').locator('.intro h2')).toHaveText('A little about me.');
 await expect(page.locator('[data-id="intro"] h2')).toHaveText('Alex Morgan');
 await page.locator('#apply-template').click();
 await expect(page.locator('dialog')).toHaveCount(0);
 await expect(page.locator('[data-id="intro"] h2')).toHaveText('Alex Morgan');
 await expect(page.locator('[data-id="intro"] h2')).toHaveCSS('font-family','Georgia, serif');
 await page.locator('#undo').click();
 await expect(page.locator('[data-id="intro"] h2')).toHaveCSS('font-family','"Space Grotesk", sans-serif');
 await page.locator('#page-menu-toggle').click();await page.locator('#templates').click();await page.locator('[data-template="professional"]').click();
 await page.locator('#keep-content').uncheck();await page.locator('#apply-template').click();
 await expect(page.locator('.intro h2')).toHaveText('Thoughtful design. Real impact.');
 await page.reload();await expect(page.locator('.intro h2')).toHaveText('Thoughtful design. Real impact.');
 await page.locator('#page-menu-toggle').click();await page.locator('#templates').click();await page.keyboard.press('Escape');await expect(page.locator('dialog')).toHaveCount(0);
});
test('resize gesture previews, commits once, and cancels without saving',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto('/');
 const handle=page.locator('.resize');let box=await handle.boundingBox();
 await page.mouse.move(box.x+9,box.y+9);await page.mouse.down();await page.mouse.move(box.x-110,box.y+9,{steps:5});
 await expect(page.locator('.resize-preview')).toContainText('Small');
 await page.mouse.up();await expect(page.locator('[data-id="project"]')).toHaveClass(/small/);
 await page.locator('#undo').click();await expect(page.locator('[data-id="project"]')).toHaveClass(/wide/);
 box=await handle.boundingBox();await page.mouse.move(box.x+9,box.y+9);await page.mouse.down();await page.mouse.move(box.x+9,box.y+100,{steps:5});
 await expect(page.locator('.resize-preview')).toContainText('Tall');await page.keyboard.press('Escape');await page.mouse.up();
 await expect(page.locator('.resize-preview')).toHaveCount(0);await expect(page.locator('[data-id="project"]')).toHaveClass(/wide/);
 await handle.focus();await page.keyboard.press('ArrowDown');await expect(page.locator('[data-id="project"]')).toHaveClass(/tall/);
});
test('upload, crop, persist and export an embedded photo',async({page})=>{
 await page.goto('/');await page.locator('[data-id="portrait"]').click();
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=200;c.height=100;const ctx=c.getContext('2d');ctx.fillStyle='red';ctx.fillRect(0,0,100,100);ctx.fillStyle='blue';ctx.fillRect(100,0,100,100);return c.toDataURL('image/png').split(',')[1]});
 await page.locator('#photo-upload').setInputFiles({name:'my-photo.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
 await expect(page.locator('#photo-status')).toContainText('Photo ready');
 await expect(page.locator('[data-id="portrait"] img')).toHaveAttribute('src',/^data:image\/webp/);
 await page.locator('[data-crop="zoom"]').fill('150');await page.locator('[data-crop="zoom"]').dispatchEvent('change');
 await page.locator('[data-crop="x"]').fill('75');await page.locator('[data-crop="x"]').dispatchEvent('change');
 await page.locator('#photo-alt').fill('Red and blue test image');await page.locator('#photo-alt').press('Tab');
 await page.locator('[data-tab="blocks"]').click();
 await page.reload();await expect(page.locator('[data-id="portrait"] img')).toHaveCSS('object-position','75% 50%');
 await expect(page.locator('[data-id="portrait"] img')).toHaveAttribute('alt','Red and blue test image');
 const pending=page.waitForEvent('download');await page.locator('#page-menu-toggle').click();await page.locator('#export').click();const download=await pending;const stream=await download.createReadStream();let html='';for await(const chunk of stream)html+=chunk;
 await page.setContent(html);await expect(page.locator('[data-id="portrait"] img')).toHaveAttribute('src',/^data:image\/webp/);
 await expect(page.locator('[data-id="portrait"] img')).toHaveCSS('transform','matrix(1.5, 0, 0, 1.5, 0, 0)');
});
test('design kit persists and exports light theme, fonts, colors and shapes',async({page})=>{
 await page.goto('/');await page.locator('#editor-theme').click();
 await expect(page.locator('html')).toHaveAttribute('data-editor-theme','light');
 await page.locator('[data-tab="design"]').click();
 await page.locator('[data-page-theme="light"]').click();
 await page.locator('[data-design="headingFont"]').selectOption('serif');
 await page.locator('[data-design="bodyFont"]').selectOption('mono');
 await page.locator('[data-hex-key="surface"]').fill('#fff4de');
 await page.locator('[data-hex-key="surface"]').press('Tab');
 await expect(page.locator('[data-id="project"]')).toHaveCSS('background-color','rgb(255, 244, 222)');
 await expect(page.locator('[data-id="project"] h2')).toHaveCSS('font-family','Georgia, serif');
 await page.getByText('Cards & layout',{exact:false}).click();
 await page.locator('[data-design="shadow"]').selectOption('lifted');
 await page.locator('#radius').fill('24');await page.locator('#radius').dispatchEvent('change');
 await page.reload();await expect(page.locator('html')).toHaveAttribute('data-editor-theme','light');
 await expect(page.locator('[data-id="project"]')).toHaveCSS('border-radius','24px');
 await page.locator('[data-tab="design"]').click();
 await page.screenshot({path:'test-results/design-light.png',fullPage:true});
 const pending=page.waitForEvent('download');await page.locator('#page-menu-toggle').click();await page.locator('#export').click();const download=await pending;
 const stream=await download.createReadStream();let html='';for await(const chunk of stream)html+=chunk;
 await page.setContent(html);await expect(page.locator('[data-id="project"]')).toHaveCSS('background-color','rgb(255, 244, 222)');
 await expect(page.locator('[data-id="project"] h2')).toHaveCSS('font-family','Georgia, serif');
 await expect(page.locator('[data-id="project"]')).toHaveCSS('border-radius','24px');
});
test('edit, persist, resize, reorder, undo and export a personal page',async({page})=>{
 // Keep source and target visible together for the native drag gesture.
 await page.setViewportSize({width:1280,height:1000});
 await page.goto('/');
 await expect(page.locator('.bento .card')).toHaveCount(9);
 await page.locator('#card-title').fill('My real project');
 await page.locator('#card-title').press('Tab');
 await expect(page.locator('[data-id="project"] h2')).toHaveText('My real project');
 await page.reload();
 await expect(page.locator('[data-id="project"] h2')).toHaveText('My real project');
 await page.locator('[data-size="tall"]').click();
 await expect(page.locator('[data-id="project"]')).toHaveClass(/tall/);
 await page.locator('#undo').click();
 await expect(page.locator('[data-id="project"]')).toHaveClass(/wide/);
 await page.locator('[data-id="project"]').dragTo(page.locator('[data-id="intro"]'));
 await expect(page.locator('.bento .card').first()).toHaveAttribute('data-id','project');
 await page.locator('[data-tab="blocks"]').click();
 await page.locator('[data-add="text"]').click();
 await expect(page.locator('.bento .card')).toHaveCount(10);
 await page.locator('#delete').click();
 await expect(page.locator('.bento .card')).toHaveCount(9);
 await page.locator('#mobile').click();
 await expect(page.locator('.canvas')).toHaveClass(/mobile-canvas/);
 await page.locator('#preview').click();
 await expect(page.locator('.card[draggable]')).toHaveCount(0);
 const downloadPromise=page.waitForEvent('download');
 await page.locator('#page-menu-toggle').click();await page.locator('#export').click();
 const download=await downloadPromise;
 expect(download.suggestedFilename()).toBe('verbaspark-page.html');
 const stream=await download.createReadStream();let html='';for await(const chunk of stream)html+=chunk;
 expect(html).toContain('My real project');expect(html).not.toContain('draggable="true"');
});
test('desktop and phone have no page overflow or runtime errors',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1440,height:1000});await page.goto('/');
 await page.screenshot({path:'test-results/editor-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.locator('[data-mobile-tool="preview"]').click();
 expect(await page.evaluate(()=>document.querySelector('.canvas').scrollWidth<=document.querySelector('.canvas').clientWidth)).toBe(true);
 expect(errors).toEqual([]);
});
test('inline text editing saves, supports undo, and cancels with Escape',async({page})=>{
 await page.goto('/');
 const title=page.locator('[data-id="project"] h2');
 await title.dblclick();
 await expect(title).toHaveAttribute('contenteditable','plaintext-only');
 await title.fill('A better interface');
 await title.press('Enter');
 await expect(title).toHaveText('A better interface');
 await expect(page.locator('#card-title')).toHaveValue('A better interface');
 await page.locator('#undo').click();
 await expect(title).toHaveText('Interface systems');
 await title.dblclick();await title.fill('Discard me');await title.press('Escape');
 await expect(title).toHaveText('Interface systems');
 await page.locator('#close-inspector').click();
 await expect(page.locator('.inspector')).toHaveCount(0);
 await expect(page.locator('[data-add="intro"]')).toBeVisible();
});

test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('verbaspark-welcome-dismissed','1'))});
