import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>page.addInitScript(()=>localStorage.setItem('verbaspark-welcome-dismissed','1')));
test('profile settings persist and preview supports translations, vCard and safe contact preview',async({page})=>{
 await page.goto('/');await page.locator('#page-menu-toggle').click();await page.locator('#profile-settings').click();
 await page.locator('[name="contactForm"]').check();await page.locator('[name="analytics"]').check();
 await page.getByText('Link preview',{exact:true}).click();await page.locator('[name="seo.title"]').fill('Ana — Portfolio');await page.locator('[name="seo.description"]').fill('My photography');
 const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=8;canvas.height=8;return canvas.toDataURL().split(',')[1]});await page.locator('#share-cover-upload').setInputFiles({name:'cover.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await expect(page.locator('#profile-settings-status')).toContainText('Cover ready');await expect(page.locator('.share-preview img')).toHaveAttribute('src',/^data:image\/webp/);
 await page.getByText('Save contact · vCard',{exact:true}).click();await page.locator('[name="vcard.enabled"]').check();await page.locator('[name="vcard.name"]').fill('Ana Novak');await page.locator('[name="vcard.email"]').fill('ana@example.com');
 await page.getByText('Languages & translations',{exact:true}).click();await page.locator('#translation-language').selectOption('sl');await page.getByLabel('Enable Slovenščina').check();await page.locator('[data-translation-name]').fill('Ana Novak');await page.locator('[data-translation-card="0"][data-field="title"]').fill('Pozdravljeni');
 await page.getByRole('button',{name:'Save settings',exact:true}).click();await page.locator('#preview').click();await page.locator('[data-profile-language]').selectOption('sl');await expect(page.locator('.intro h2')).toHaveText('Pozdravljeni');
 const download=page.waitForEvent('download');await page.locator('.vcard-download').click();expect((await download).suggestedFilename()).toBe('contact.vcf');
 const form=page.locator('[data-contact-form]');await form.locator('[name="name"]').fill('Guest');await form.locator('[name="email"]').fill('guest@example.com');await form.locator('[name="message"]').fill('Hello');await form.locator('button').click();await expect(form.locator('[role="status"]')).toContainText('objavljeni');
 await page.reload();await page.locator('#page-menu-toggle').click();await page.locator('#profile-settings').click();await expect(page.locator('[name="contactForm"]')).toBeChecked();await page.getByText('Link preview',{exact:true}).click();await expect(page.locator('[name="seo.title"]')).toHaveValue('Ana — Portfolio');await expect(page.locator('.share-preview img')).toHaveAttribute('src',/^data:image\/webp/);
 await page.setViewportSize({width:390,height:844});expect(await page.locator('.profile-settings').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:'test-results/profile-settings-mobile.png'});
});
test('local file library reuses an attachment without uploading it again',async({page})=>{
 await page.goto('/');await page.locator('[data-tab="blocks"]').click();await page.locator('[data-add="document"]').click();await page.locator('#file-upload').setInputFiles({name:'price-list.txt',mimeType:'text/plain',buffer:Buffer.from('Services and prices')});
 await page.locator('#page-menu-toggle').click();await page.locator('#file-library').click();await page.getByLabel('File type').selectOption('document');await page.locator('.library-file').filter({hasText:'price-list.txt'}).getByRole('button',{name:'Add to page'}).click();await expect(page.locator('.card.document')).toHaveCount(2);
});
