import test from 'node:test';
import assert from 'node:assert/strict';
import {Autosave} from '../src/autosave.js';
const doc=name=>({name,cards:[]});
function setup(){const rows=new Map();let remoteRow=null,fail=false,writes=[];const store={list:async()=>[...rows.values()].sort((a,b)=>b.time-a.time),write:async row=>{rows.set(row.id,structuredClone(row))}};const remote={read:async()=>structuredClone(remoteRow),resolve:async x=>x,write:async(document,options)=>{writes.push({document:structuredClone(document),...options});if(fail)throw Error('Network unavailable');if(remoteRow&&options.revision!==remoteRow.revision)throw Object.assign(Error('DRAFT_CONFLICT'),{code:'VS409'});remoteRow={document:structuredClone(document),revision:(remoteRow?.revision||0)+1,last_save_id:options.requestId};return remoteRow.revision}};const manager=new Autosave({store,remote,delay:60000,retryDelay:60000,online:()=>true});return {manager,store,remote,writes,rows,setRemote:value=>{remoteRow=value},getRemote:()=>remoteRow,fail:value=>{fail=value}};}
test('local recovery survives reload, including pending sync metadata',async()=>{const s=setup();await s.manager.start(doc('First'));s.manager.edit(doc('Latest'));await s.manager.localQueue;const recovered=new Autosave({store:s.store,remote:s.remote});assert.equal((await recovered.start(doc('Empty'))).name,'Latest');assert.equal(recovered.status().localDurable,true);s.manager.dispose();recovered.dispose()});
test('autosave updates drafts only and retries after a failed write',async()=>{const s=setup();await s.manager.start(doc('A'));await s.manager.connect({id:'alice'});s.fail(true);await assert.rejects(s.manager.flush(),/Network/);assert.equal(s.manager.status().cloud,'error');assert.equal(s.manager.status().localDurable,true);s.fail(false);await s.manager.flush();assert.equal(s.manager.status().cloud,'saved');assert.equal(s.getRemote().document.name,'A');s.manager.dispose()});
test('existing remote draft requires a choice, and conflicts never overwrite it',async()=>{const s=setup();s.setRemote({document:doc('Other device'),revision:5});await s.manager.start(doc('Local'));await s.manager.connect({id:'alice'});assert.equal(s.manager.block,'choose');await assert.rejects(s.manager.flush(),/Choose/);assert.equal(s.writes.length,0);await s.manager.chooseLocal();s.setRemote({document:doc('New remote'),revision:7});s.manager.edit(doc('My edits'));await assert.rejects(s.manager.flush(),/DRAFT_CONFLICT/);assert.equal(s.getRemote().document.name,'New remote');assert.equal(s.manager.row.document.name,'My edits');s.manager.dispose()});
test('edits during an in-flight save are serialized and acknowledged separately',async()=>{const s=setup();await s.manager.start(doc('A'));await s.manager.connect({id:'alice'});let release;const write=s.remote.write;s.remote.write=async(...args)=>{if(args[0].name==='A')await new Promise(resolve=>{release=resolve});return write(...args)};const running=s.manager.flush();await new Promise(resolve=>setImmediate(resolve));s.manager.edit(doc('B'));release();await running;assert.deepEqual(s.writes.map(w=>w.document.name),['A','B']);assert.deepEqual(s.writes.map(w=>w.revision),[null,1]);assert.equal(s.getRemote().document.name,'B');s.manager.dispose()});
test('account changes never auto-upload a previous account’s page',async()=>{const s=setup();await s.manager.start(doc('Alice private'));await s.manager.connect({id:'alice'});await s.manager.flush();await s.manager.connect(null);s.setRemote(null);await s.manager.connect({id:'bob'});assert.equal(s.manager.block,'account');await assert.rejects(s.manager.flush(),/Choose/);assert.equal(s.writes.length,1);s.manager.dispose()});
test('local quota failures preserve the open document and flag unsaved changes',async()=>{const s=setup();await s.manager.start(doc('Safe'));s.store.write=async()=>{throw Error('Quota exceeded')};s.manager.edit(doc('Still visible'));await s.manager.localQueue;assert.equal(s.manager.row.document.name,'Still visible');assert.equal(s.manager.status().local,'error');assert.equal(s.manager.status().localDurable,false);assert.equal((await s.store.list())[0].document.name,'Safe');s.manager.dispose()});
test('offline edits are persisted and reconnect resumes the pending draft',async()=>{const s=setup();let online=true;s.manager.online=()=>online;await s.manager.start(doc('A'));await s.manager.connect({id:'alice'});await s.manager.flush();online=false;s.manager.edit(doc('Offline edit'));await s.manager.localQueue;assert.equal(s.manager.cloudState,'offline');assert.equal(s.writes.length,1);online=true;await s.manager.reconnect();await s.manager.flush();assert.equal(s.getRemote().document.name,'Offline edit');s.manager.dispose()});
test('loading a remote draft keeps a recoverable local version',async()=>{const s=setup();s.setRemote({document:doc('Remote'),revision:2});await s.manager.start(doc('Keep me'));await s.manager.connect({id:'alice'});await s.manager.loadOnline();assert.equal(s.manager.row.document.name,'Remote');assert.ok((await s.store.list()).some(row=>row.document.name==='Keep me'));s.manager.dispose()});
