import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('database enforces owners, revisions, idempotency and separate publication snapshots',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key,bucket_id text,name text);alter table storage.objects enable row level security;
 create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;
 grant usage on schema public,auth,storage to anon,authenticated;
 grant select,insert on storage.objects to anon,authenticated;
 insert into auth.users values('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb');`);
 for(const file of ['001_accounts.sql','002_gallery_images.sql','003_autosave.sql','004_page_files.sql','005_hidden_blocks.sql','007_share_covers.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));
 const login=async(id,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role '+role)};
 const save=(name,rev,id)=>db.query("select public.save_draft($1::jsonb,$2::bigint,$3::uuid,'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa') as revision",[JSON.stringify({name,cards:[]}),rev,id]);
 await login('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');
 const id1='11111111-1111-4111-8111-111111111111',id2='22222222-2222-4222-8222-222222222222';
 assert.equal((await save('First',null,id1)).rows[0].revision,1);
 await db.query("select public.publish_page('alice',1,'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')");
 assert.equal((await save('Private update',1,id2)).rows[0].revision,2);
 assert.equal((await save('Private update',1,id2)).rows[0].revision,2);
 await assert.rejects(save('Stale',1,'33333333-3333-4333-8333-333333333333'),/DRAFT_CONFLICT/);
 await assert.rejects(db.query("select public.publish_page('alice',1,'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')"),/DRAFT_CONFLICT/);
 await assert.rejects(db.query("update public.drafts set document='{}'"),/permission denied/);
 await login('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb');assert.equal((await db.query('select * from public.drafts')).rows.length,0);
 await assert.rejects(db.query("select public.publish_page('bob',1,'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb')"),/DRAFT_CONFLICT/);
 await assert.rejects(save('Wrong account',null,'44444444-4444-4444-8444-444444444444'),/Account changed/);
 await login('','anon');assert.equal((await db.query('select document from public.published_pages')).rows[0].document.name,'First');
 await assert.rejects(save('Anonymous',null,id1),/permission denied/);
 await login('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');await db.query("select public.publish_page('alice',2,'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')");
 assert.equal((await db.query('select document from public.published_pages')).rows[0].document.name,'Private update');
 const filePath='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/'+ 'a'.repeat(64)+'.pdf';
 await db.query("insert into storage.objects(id,bucket_id,name) values('55555555-5555-4555-8555-555555555555','page-files',$1)",[filePath]);
 await login('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb');assert.equal((await db.query("select * from storage.objects where bucket_id='page-files'")).rows.length,0);
 await assert.rejects(db.query("insert into storage.objects(id,bucket_id,name) values('66666666-6666-4666-8666-666666666666','page-files',$1)",[filePath]),/row-level security/);
 await login('','anon');assert.equal((await db.query("select * from storage.objects where bucket_id='page-files'")).rows.length,0);
 await login('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');
 await db.query("select public.save_draft($1,2,'77777777-7777-4777-8777-777777777777','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')",[JSON.stringify({cards:[{type:'document',file:{path:filePath}}]})]);
 await db.query("select public.publish_page('alice',3,'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')");
 await login('','anon');assert.equal((await db.query("select * from storage.objects where bucket_id='page-files'")).rows.length,1);
 await login('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');
 await db.query("select public.save_draft($1,3,'88888888-8888-4888-8888-888888888888','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')",[JSON.stringify({cards:[{type:'document',hidden:true,title:'Private CV',file:{path:filePath}},{type:'text',title:'Visible'}]})]);
 await db.query("select public.publish_page('alice',4,'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')");
 assert.equal((await db.query('select document from public.drafts')).rows[0].document.cards.length,2);
 await login('','anon');assert.deepEqual((await db.query('select document from public.published_pages')).rows[0].document.cards,[{type:'text',title:'Visible'}]);assert.equal((await db.query("select * from storage.objects where bucket_id='page-files'")).rows.length,0);
 await login('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');await db.query('delete from public.published_pages');
 await login('','anon');assert.equal((await db.query("select * from storage.objects where bucket_id='page-files'")).rows.length,0);
 await login('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');
 const cover='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/'+'b'.repeat(64)+'.webp';
 await db.query("insert into storage.objects(id,bucket_id,name) values('99999999-9999-4999-8999-999999999999','page-images',$1)",[cover]);
 await db.query("select public.save_draft($1,4,'99999999-9999-4999-8999-999999999999','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')",[JSON.stringify({cards:[],profile:{seo:{imagePath:cover}}})]);
 await login('','anon');assert.equal((await db.query("select * from storage.objects where bucket_id='page-images'")).rows.length,0);
 await login('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');await db.query("select public.publish_page('alice',5,'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')");
 await login('','anon');assert.equal((await db.query("select * from storage.objects where bucket_id='page-images'")).rows.length,1);
 await login('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');await db.query('delete from public.published_pages');
 await login('','anon');assert.equal((await db.query("select * from storage.objects where bucket_id='page-images'")).rows.length,0);
 }finally{await db.close()}
});
