import {chromium} from '@playwright/test';
import {fileURLToPath} from 'node:url';

const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1200,height:630},deviceScaleFactor:1});
 await page.setContent(`<!doctype html><html><head><style>
 *{box-sizing:border-box}body{margin:0;background:#111916;color:#f7fff8;font-family:Arial,sans-serif}.frame{width:1200px;height:630px;padding:52px 64px;position:relative;overflow:hidden;background:radial-gradient(circle at 88% 12%,#194b3b 0%,transparent 38%),#111916}.brand{font-size:29px;font-weight:800;letter-spacing:-.065em}.brand span{color:#32d4a8;font-size:36px;margin-right:8px}.eyebrow{font:700 15px monospace;letter-spacing:.16em;color:#5fe6ba;margin-top:96px}.headline{font-size:91px;line-height:1.02;letter-spacing:-.075em;font-weight:800;margin-top:25px}.headline em{font-style:normal;color:#42d5aa}.sub{font-size:24px;color:#bdd5c8;line-height:1.4;margin-top:24px}.mockup{position:absolute;right:66px;top:92px;width:350px;height:448px;background:#1c2b25;border:1px solid #5a8a72;border-radius:25px;box-shadow:17px 18px 0 #244338;transform:rotate(6deg);padding:17px}.mocktop{font:700 13px monospace;color:#75dbb3;margin-bottom:18px}.card{background:#274136;border-radius:14px;padding:25px;height:207px}.card small{font:700 11px monospace;letter-spacing:.12em;color:#9eeaca}.card strong{display:block;font-size:54px;letter-spacing:-.065em;line-height:.95;margin-top:20px}.card strong span{color:#45d5a9}.card p{font-size:15px;color:#c8dfd1}.tiles{display:flex;gap:10px;margin-top:10px}.tiles div{height:120px;flex:1;border-radius:13px;background:#51a784}.tiles div:last-child{background:#d7f567;color:#1c361f;font-size:35px;padding:15px}
 </style></head><body><div class="frame"><div class="brand"><span>✦</span> Verbaspark</div><div class="eyebrow">YOUR CORNER OF THE INTERNET</div><div class="headline">More you.<br><em>Less link list.</em></div><div class="sub">Your story, work and links in one place.</div><div class="mockup"><div class="mocktop">✦ alex.morgan &nbsp; ● LIVE</div><div class="card"><small>HELLO, WORLD</small><strong>Alex<br>Morgan<span>.</span></strong><p>Designer & developer.</p></div><div class="tiles"><div></div><div>↗</div></div></div></div></body></html>`);
 await page.screenshot({path:fileURLToPath(new URL('../public/og-verbaspark.png',import.meta.url))});
}finally{await browser.close()}
