import {cleanFields,fieldTypes} from './contact-fields.js';
import {icon} from './icons.js';
export function openContactEditor(profile,save,focusField){
 const fields=cleanFields(profile?.contactFields);const dialog=document.createElement('dialog');dialog.className='account-dialog contact-editor';dialog.setAttribute('aria-label','Contact form');dialog.innerHTML=`<button class="account-close" aria-label="Close contact form">${icon('close')}</button><h2>Contact form</h2><p>Choose the fields visitors fill in. Move the form directly in the page editor.</p><label class="setting-toggle"><input id="contact-enabled" type="checkbox" checked> Show contact form</label><label>Confirmation message<textarea id="contact-success" maxlength="500" rows="3" placeholder="Message sent. Thank you!"></textarea></label><p class="hint">Shown after a successful submission. Leave empty for the default message.</p><div id="contact-fields"></div><button id="add-contact-field">+ Add field</button><p class="hint">Up to 12 fields. Changes go live when you publish again.</p><p role="status"></p><button id="save-contact-form" class="primary">Save form</button>`;
 dialog.querySelector('#contact-success').value=profile?.contactSuccess||'';document.body.append(dialog);dialog.showModal();dialog.onclose=()=>dialog.remove();dialog.querySelector('.account-close').onclick=()=>dialog.close();
 const render=()=>{const list=dialog.querySelector('#contact-fields');list.replaceChildren();fields.forEach((field,index)=>{const row=document.createElement('section');row.className='contact-field-editor';row.dataset.fieldId=field.id;const label=document.createElement('label');label.textContent='Field label';const input=document.createElement('input');input.value=field.label;input.maxLength=100;input.oninput=()=>field.label=input.value;label.append(input);const typeLabel=document.createElement('label');typeLabel.textContent='Field type';const select=document.createElement('select');for(const [value,text] of Object.entries(fieldTypes)){const option=document.createElement('option');option.value=value;option.textContent=text;option.selected=field.type===value;select.append(option)}select.onchange=()=>{field.type=select.value;render()};typeLabel.append(select);const required=document.createElement('label');required.className='setting-toggle';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=field.required;checkbox.onchange=()=>field.required=checkbox.checked;required.append(checkbox,' Required');row.append(label,typeLabel,required);if(field.type==='select'){const label=document.createElement('label');label.textContent='Options (one per line)';const textarea=document.createElement('textarea');textarea.value=field.options.join('\n');textarea.rows=3;textarea.maxLength=2000;textarea.oninput=()=>field.options=textarea.value.split('\n');label.append(textarea);row.append(label)}const actions=document.createElement('div');actions.className='contact-field-actions';for(const [name,fn,disabled] of [['Move up',()=>{[fields[index-1],fields[index]]=[field,fields[index-1]];render()},index===0],['Move down',()=>{[fields[index+1],fields[index]]=[field,fields[index+1]];render()},index===fields.length-1],['Remove',()=>{fields.splice(index,1);render()},false]]){const button=document.createElement('button');button.textContent=name;button.disabled=disabled;button.onclick=fn;actions.append(button)}row.append(actions);list.append(row)});dialog.querySelector('#add-contact-field').disabled=fields.length>=12};
 dialog.querySelector('#add-contact-field').onclick=()=>{if(fields.length>=12)return;fields.push({id:'field_'+crypto.randomUUID(),label:'New field',type:'text',required:false,options:[]});render();dialog.querySelector('#contact-fields section:last-child input').focus()};
 dialog.querySelector('#save-contact-form').onclick=()=>{const enabled=dialog.querySelector('#contact-enabled').checked,clean=cleanFields(fields);if(enabled&&(!clean.length||fields.some(f=>!f.label.trim())||clean.some(f=>f.type==='select'&&!f.options.length))){dialog.querySelector('[role=status]').textContent='Add at least one field, label every field, and provide dropdown options.';return}save({contactForm:enabled,contactFields:clean,contactSuccess:dialog.querySelector('#contact-success').value.trim().slice(0,500)});dialog.close()};render();if(focusField){const field=[...dialog.querySelectorAll('[data-field-id]')].find(el=>el.dataset.fieldId===focusField);field?.scrollIntoView({block:'center'});field?.querySelector('input').focus()}
}
