import {icon} from './icons.js';
export const fonts={grotesk:"'Space Grotesk', sans-serif",sans:"'DM Sans', sans-serif",system:'system-ui, sans-serif',serif:'Georgia, serif',mono:'ui-monospace, monospace'};
const palettes={dark:{background:'#101318',surface:'#1b2029',text:'#e9ecf3',muted:'#b0bccd',border:'#303744'},light:{background:'#f3f5f9',surface:'#ffffff',text:'#182335',muted:'#526177',border:'#d8dfea'}};
export const defaults={mode:'dark',headingFont:'grotesk',bodyFont:'sans',fontSize:13,headingScale:100,lineHeight:1.65,weight:500,padding:24,borderWidth:1,shadow:'none',buttonStyle:'solid',buttonRadius:5,...palettes.dark};
export function initDesign(state){state.design={...defaults,...state.design};state.editorTheme??='dark';}
export function tokens(state){const d=state.design;return {'--accent':state.accent,'--accent-contrast':contrast(state.accent),'--gap':state.gap+'px','--radius':state.radius+'px','--page-bg':d.background,'--page-surface':d.surface,'--page-text':d.text,'--page-muted':d.muted,'--page-border':d.border,'--heading-font':fonts[d.headingFont]||fonts.grotesk,'--body-font':fonts[d.bodyFont]||fonts.sans,'--body-size':d.fontSize+'px','--heading-scale':d.headingScale/100,'--line-height':d.lineHeight,'--heading-weight':d.weight,'--card-padding':d.padding+'px','--card-border-width':d.borderWidth+'px','--card-shadow':{none:'none',soft:'0 5px 20px #00000012',lifted:'0 12px 30px #00000026'}[d.shadow],'--button-radius':d.buttonRadius+'px','--button-bg':d.buttonStyle==='solid'?state.accent:'transparent','--button-text':d.buttonStyle==='solid'?contrast(state.accent):state.accent};}
function contrast(hex){const c=hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722>.179?'#111827':'#ffffff'}
export function applyDesign(state){initDesign(state);document.documentElement.dataset.editorTheme=state.editorTheme;for(const [key,value] of Object.entries(tokens(state)))document.documentElement.style.setProperty(key,value);}
export function styleString(state){return Object.entries(tokens(state)).map(([k,v])=>`${k}:${v}`).join(';')}
export function designPanel(state,esc){const d=state.design;
 const select=(key,label,options)=>`<label>${label}<select data-design="${key}">${Object.entries(options).map(([value,name])=>`<option value="${value}" ${String(d[key])===value?'selected':''}>${name}</option>`).join('')}</select></label>`;
 const range=(key,label,min,max,step=1,unit='px')=>`<label>${label}<output>${d[key]}${unit}</output><input data-design="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${d[key]}"></label>`;
 return `<section class="design-controls"><div class="section-label">PAGE DESIGN <button id="reset-design" title="Reset styling, keep all content">Reset</button></div><p class="hint">Your page’s own visual identity.</p><label>Page layout<select id="page-layout"><option value="bento" ${state.layout!=='classic'?'selected':''}>Bento grid</option><option value="classic" ${state.layout==='classic'?'selected':''}>Classic profile</option></select></label><label>Page name<input id="page-name" value="${esc(state.name)}"></label><div class="theme-options">${['light','dark'].map(mode=>`<button data-page-theme="${mode}" aria-pressed="${d.mode===mode}"><span>${icon(mode==='light'?'sun':'moon')}</span> ${mode==='light'?'Light':'Dark'}</button>`).join('')}</div>
 <details open><summary>Colors <span>01</span></summary><div class="palette-presets">${['Original','Paper','Sage','Lavender'].map(name=>`<button data-preset="${name}">${name}</button>`).join('')}</div>${Object.entries({accent:'Accent',background:'Background',surface:'Cards',text:'Headings',muted:'Body text',border:'Borders'}).map(([key,label])=>`<label class="color-row">${label}<span><input type="color" aria-label="${label} color" data-color-key="${key}" value="${key==='accent'?state.accent:d[key]}"><input type="text" aria-label="${label} hex" data-hex-key="${key}" value="${key==='accent'?state.accent:d[key]}" pattern="#[0-9a-fA-F]{6}" maxlength="7"></span></label>`).join('')}</details>
 <details open><summary>Typography <span>02</span></summary>${select('headingFont','Heading font',{grotesk:'Space Grotesk',sans:'DM Sans',system:'System sans',serif:'Georgia',mono:'Monospace'})}${select('bodyFont','Body font',{sans:'DM Sans',grotesk:'Space Grotesk',system:'System sans',serif:'Georgia',mono:'Monospace'})}${range('fontSize','Body size',11,20)}${range('headingScale','Heading scale',80,125,5,'%')}${select('weight','Heading weight',{'400':'Regular','500':'Medium','600':'Semibold','700':'Bold'})}${range('lineHeight','Line height',1.2,2,.05,'×')}<div class="type-sample" style="font-family:${fonts[d.headingFont]}">Aa Bb Cc <small>The details make it yours.</small></div></details>
 <details><summary>Cards & layout <span>03</span></summary><label>Grid gap <output>${state.gap}px</output><input id="gap" type="range" min="8" max="28" value="${state.gap}"></label><label>Corner radius <output>${state.radius}px</output><input id="radius" type="range" min="0" max="32" value="${state.radius}"></label>${range('padding','Card padding',16,36)}${range('borderWidth','Border width',0,3)}${select('shadow','Shadow',{none:'None',soft:'Soft',lifted:'Lifted'})}</details>
 <details><summary>Buttons <span>04</span></summary>${select('buttonStyle','Button style',{solid:'Solid',outline:'Outline'})}${range('buttonRadius','Button radius',0,28)}<span class="button-sample">Get in touch ↗</span></details></section>`;
}
export function bindDesign(state,change,render){const update=(key,value)=>change(()=>{state.design[key]=value});
 document.querySelector('#editor-theme')?.addEventListener('click',()=>change(()=>{state.editorTheme=state.editorTheme==='dark'?'light':'dark'}));
 document.querySelectorAll('[data-page-theme]').forEach(b=>b.onclick=()=>change(()=>{state.design={...state.design,mode:b.dataset.pageTheme,...palettes[b.dataset.pageTheme]}}));
 document.querySelectorAll('[data-design]').forEach(el=>el.onchange=()=>update(el.dataset.design,el.type==='range'||el.dataset.design==='weight'?Number(el.value):el.value));
 const color=(key,value)=>{if(!/^#[0-9a-f]{6}$/i.test(value))return false;change(()=>{if(key==='accent')state.accent=value;else state.design[key]=value});return true};
 document.querySelectorAll('[data-color-key]').forEach(el=>el.onchange=()=>color(el.dataset.colorKey,el.value));
 document.querySelectorAll('[data-hex-key]').forEach(el=>el.onchange=()=>{if(!color(el.dataset.hexKey,el.value)){el.setCustomValidity('Use a six-digit hex color, such as #448aff.');el.reportValidity()} });
 document.querySelectorAll('[data-hex-key]').forEach(el=>el.oninput=()=>el.setCustomValidity(''));
 document.querySelector('#reset-design')?.addEventListener('click',()=>change(()=>{state.design={...defaults};state.accent='#448aff';state.gap=16;state.radius=12}));
 document.querySelectorAll('[data-preset]').forEach(el=>el.onclick=()=>change(()=>{const name=el.dataset.preset;const light=name!=='Original';state.design={...defaults,mode:light?'light':'dark',...palettes[light?'light':'dark']};state.accent={Original:'#448aff',Paper:'#2563eb',Sage:'#28745b',Lavender:'#7753c9'}[name];if(name==='Sage')Object.assign(state.design,{background:'#edf3ee',surface:'#f9fcf8',headingFont:'serif'});if(name==='Lavender')Object.assign(state.design,{background:'#f1eef8',surface:'#fcfaff'});state.radius=name==='Original'?12:18}));
 document.querySelectorAll('.design-controls input[type="range"]').forEach(el=>el.addEventListener('input',()=>{const output=el.closest('label').querySelector('output');if(output)output.textContent=el.value+(el.dataset.design==='headingScale'?'%':el.dataset.design==='lineHeight'?'×':'px')}));
}
