import {cloud} from './cloud.js';
import {toolDialog,requireUser} from './profile-tools.js';
import {bytesLabel,fileTypes} from './files.js';
export async function openFileLibrary(state,add,chooseImage){
 const {dialog,content,message}=toolDialog('File library');const summary=document.createElement('p'),cleanup=document.createElement('button'),filter=document.createElement('select'),list=document.createElement('div');list.className='file-library-list';cleanup.type='button';cleanup.hidden=true;for(const [value,title] of [['all','All files'],['image','Images'],['document','Documents'],['audio','Audio']]){const option=document.createElement('option');option.value=value;option.textContent=title;filter.append(option)}filter.setAttribute('aria-label','File type');if(chooseImage){filter.value='image';filter.hidden=true}content.append(summary,cleanup,filter,list);message('Loading files…');
 const items=new Map();const remember=(key,item)=>{if(!items.has(key))items.set(key,item)};
 for(const card of [...state.cards,...(state.profile?.seo?.image||state.profile?.seo?.imagePath?[{...state.profile.seo,title:'Share cover'}]:[]),...(state.showcaseCover?.image||state.showcaseCover?.imagePath?[{...state.showcaseCover,title:'Showcase cover'}]:[])]){for(const photo of [card,...(card.images||[])]){if(photo.image||photo.imagePath)remember('page-images:'+(photo.imagePath||photo.image),{kind:'image',name:photo.alt||photo.caption||card.title||'Photo',size:photo.image?.startsWith('data:')?Math.floor(photo.image.split(',')[1].length*.75):0,bucket:'page-images',path:photo.imagePath,source:photo.image})}if(card.file)remember('page-files:'+(card.file.path||card.file.src),{kind:card.file.mime.startsWith('audio/')?'audio':'document',name:card.file.name,size:card.file.size,bucket:'page-files',path:card.file.path,source:card.file.src,mime:card.file.mime})}
 const render=()=>{list.replaceChildren();for(const item of items.values()){if(filter.value!=='all'&&filter.value!==item.kind)continue;const row=document.createElement('div');row.className='library-file';const title=document.createElement('strong');title.textContent=item.name;const detail=document.createElement('small');detail.textContent=item.kind+' · '+(item.size?bytesLabel(item.size):'External / size unknown')+(item.path?' · saved online':' · current page');const button=document.createElement('button');button.textContent=chooseImage?'Use as Showcase cover':'Add to page';button.onclick=async()=>{button.disabled=true;try{let src=item.source;if(item.path){await requireUser();const result=await cloud.storage.from(item.bucket).createSignedUrl(item.path,3600);if(result.error)throw result.error;src=result.data.signedUrl}if(!dialog.isConnected)return;if(chooseImage)chooseImage({image:src,imagePath:item.path||'',alt:item.name});else if(item.kind==='image')add({type:'photo',title:item.name,image:src,...(item.path?{imagePath:item.path}:{})});else add({type:item.kind==='audio'?'audio':'document',title:item.name,file:{name:item.name,mime:item.mime,size:item.size,src,...(item.path?{path:item.path}:{})}});dialog.close()}catch(error){message(error.message);button.disabled=false}};row.append(title,detail,button);list.append(row)}if(!list.children.length)list.textContent='No files in this category.'};filter.onchange=render;render();
 try{const user=await requireUser();let used=0,count=0;for(const bucket of ['page-images','page-files'])for(let offset=0;;offset+=100){const {data,error}=await cloud.storage.from(bucket).list(user.id,{limit:100,offset,sortBy:{column:'name',order:'asc'}});if(error)throw error;for(const file of data){if(!file.id)continue;const path=user.id+'/'+file.name,size=Number(file.metadata?.size)||0,mime=file.metadata?.mimetype||fileTypes[file.name.split('.').pop()]||'',key=bucket+':'+path;used+=size;count++;const old=items.get(key);items.set(key,{...old,kind:bucket==='page-images'?'image':mime.startsWith('audio/')?'audio':'document',name:old?.name||file.name,size,bucket,path,mime})}if(data.length<100)break}if(!dialog.isConnected)return;summary.textContent=`${count} online files · ${bytesLabel(used)} stored`;render();
  const usage=async action=>{const {data}=await cloud.auth.getSession();if(!data.session)throw Error('Sign in again.');const preserve=[];for(const card of [...state.cards,state.profile?.seo,state.showcaseCover])for(const item of [card,...(card?.images||[])]){if(item?.imagePath)preserve.push('page-images:'+item.imagePath);if(item?.file?.path)preserve.push('page-files:'+item.file.path)}const response=await fetch('/api/storage',{method:action?'POST':'GET',headers:{Authorization:'Bearer '+data.session.access_token,...(action?{'Content-Type':'application/json'}:{})},body:action?JSON.stringify({action,preserve:[...new Set(preserve)]}):undefined});const result=await response.json();if(!response.ok)throw Error(result.error||'Storage is unavailable.');return result};
  const show=report=>{summary.textContent=`${report.count} online files · ${bytesLabel(report.used)} of ${bytesLabel(report.quota)} used`;cleanup.textContent=`Remove ${report.unusedCount} unused files (${bytesLabel(report.unusedBytes)})`;cleanup.hidden=!report.unusedCount;message(report.cleaned?`Removed ${report.cleaned.removed} files. Refresh the library to update the list.`:'Only uploads older than 30 days and absent from both your online draft and published page can be removed.');};
  try{show(await usage())}catch(error){message('Usage details unavailable. '+error.message)}
  cleanup.onclick=async()=>{if(!window.confirm('Remove these unused uploads permanently? Files used in your online draft or published page are protected.'))return;cleanup.disabled=true;message('Checking current references and removing unused files…');try{show(await usage('cleanup'))}catch(error){message(error.message)}finally{cleanup.disabled=false}};
 }catch(error){summary.textContent=`${items.size} files referenced by this draft`;message('Online storage could not be loaded. '+error.message)}
}
