import {preparePhoto,imageSource} from './photos.js';
export function galleryHTML(card,esc,editing){const tag=editing?'div':'button';return `<div class="gallery-photos ${card.galleryMode==='slider'?'gallery-slider':'gallery-grid'}" ${card.galleryMode==='slider'&&!editing?'tabindex="0" role="group" aria-label="Photo gallery. Use left and right arrow keys."':''} style="--gallery-gap:${Number(card.galleryGap??8)}px;--gallery-radius:${Number(card.galleryRadius??8)}px">${(card.images||[]).map((p,i)=>`<${tag} class="gallery-item" ${editing?'':`type="button" data-gallery-open="${i}" aria-label="Open photo ${i+1}"`}><img src="${esc(imageSource(p.image))}" alt="${esc(p.caption||'Gallery photo '+(i+1))}" loading="lazy">${p.caption?`<span>${esc(p.caption)}</span>`:''}</${tag}>`).join('')||'<div class="gallery-empty">Your photos belong here.<br>Add images in the Gallery settings.</div>'}</div>${!editing&&card.galleryMode==='slider'&&(card.images||[]).length>1?'<div class="gallery-navigation"><button type="button" data-gallery-step="-1" aria-label="Previous gallery photos"><svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 12H4m6-6-6 6 6 6"/></svg></button><span class="gallery-position" aria-live="polite" aria-atomic="true">1 / '+(card.images||[]).length+'</span><button type="button" data-gallery-step="1" aria-label="Next gallery photos"><svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 12h16m-6-6 6 6-6 6"/></svg></button></div>':''}`}
export function galleryPanel(card,esc){return `<section class="gallery-settings"><label class="upload-zone"><svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg> Add photos<input id="gallery-upload" type="file" accept="image/jpeg,image/png,image/webp" multiple><small>Up to 12 photos · 15 MB each</small></label><p id="gallery-status" role="status" class="hint"></p><label>Layout<select id="gallery-mode"><option value="grid" ${card.galleryMode!=='slider'?'selected':''}>Grid</option><option value="slider" ${card.galleryMode==='slider'?'selected':''}>Slider</option></select></label><label>Photo spacing<input id="gallery-gap" type="range" min="0" max="24" value="${card.galleryGap??8}"></label><label>Photo corners<input id="gallery-radius" type="range" min="0" max="24" value="${card.galleryRadius??8}"></label><div class="gallery-image-list">${(card.images||[]).map((p,i)=>`<div class="gallery-image-row"><img src="${esc(imageSource(p.image))}" alt=""><label>Photo ${i+1} caption<input data-caption="${i}" value="${esc(p.caption||'')}" maxlength="300"></label><div><button data-image-move="${i}" data-direction="-1" ${i===0?'disabled':''} aria-label="Move photo ${i+1} earlier"><svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 20V4m-6 6 6-6 6 6"/></svg></button><button data-image-move="${i}" data-direction="1" ${i===(card.images.length-1)?'disabled':''} aria-label="Move photo ${i+1} later"><svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 4v16m-6-6 6 6 6-6"/></svg></button><button data-image-remove="${i}" aria-label="Remove photo ${i+1}"><svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button></div></div>`).join('')}</div></section>`}
export function bindGallery(state,selected,change){const card=state.cards.find(c=>c.id===selected);const upload=document.querySelector('#gallery-upload');if(!upload||card?.type!=='gallery')return;
 const status=message=>{const el=document.querySelector('#gallery-status');if(el)el.textContent=message};
 const add=async files=>{if(!files.length)return;if((card.images||[]).length+files.length>12){status('A gallery can contain up to 12 photos.');return}upload.disabled=true;status('Preparing photos…');try{const images=[];for(const file of files)images.push({image:await preparePhoto(file),caption:''});if(!state.cards.includes(card))return;change(()=>card.images=[...(card.images||[]),...images]);status('Photos added and saved.')}catch(error){status(error.message)}finally{upload.disabled=false}};
 upload.onchange=e=>add([...e.target.files]);const zone=upload.closest('.upload-zone');zone.ondragover=e=>e.preventDefault();zone.ondrop=e=>{e.preventDefault();add([...e.dataTransfer.files])};
 for(const [id,key] of [['gallery-mode','galleryMode'],['gallery-gap','galleryGap'],['gallery-radius','galleryRadius']])document.getElementById(id).onchange=e=>change(()=>card[key]=key==='galleryMode'?e.target.value:Number(e.target.value));
 document.querySelectorAll('[data-caption]').forEach(el=>el.onchange=()=>change(()=>card.images[Number(el.dataset.caption)].caption=el.value));
 document.querySelectorAll('[data-image-remove]').forEach(el=>el.onclick=()=>change(()=>card.images.splice(Number(el.dataset.imageRemove),1)));
 document.querySelectorAll('[data-image-move]').forEach(el=>el.onclick=()=>change(()=>{const i=Number(el.dataset.imageMove),j=i+Number(el.dataset.direction);[card.images[i],card.images[j]]=[card.images[j],card.images[i]]}));
}
// Self-contained so exported HTML can use the same keyboard-accessible viewer.
export function galleryRuntime(){
 const position=rail=>{const items=[...rail.querySelectorAll('.gallery-item')],max=Math.max(0,rail.scrollWidth-rail.clientWidth),start=rail.getBoundingClientRect().left;const stops=items.map(item=>Math.min(max,item.getBoundingClientRect().left-start+rail.scrollLeft));let index=0;stops.forEach((stop,i)=>{if(Math.abs(stop-rail.scrollLeft)<Math.abs(stops[index]-rail.scrollLeft))index=i});return {items,stops,index,max}};
 const update=rail=>{const nav=rail.nextElementSibling;if(!nav?.classList.contains('gallery-navigation'))return;const {items,index,max}=position(rail);nav.querySelector('.gallery-position').textContent=(index+1)+' / '+items.length;nav.querySelector('[data-gallery-step="-1"]').disabled=rail.scrollLeft<=1;nav.querySelector('[data-gallery-step="1"]').disabled=rail.scrollLeft>=max-1};
 const moveRail=(rail,step)=>{const {stops,index}=position(rail);rail.scrollTo({left:stops[Math.max(0,Math.min(stops.length-1,index+step))]||0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})};
 document.querySelectorAll('.gallery-slider').forEach(update);
 if(document.body.dataset.galleryReady)return;document.body.dataset.galleryReady='true';
 document.addEventListener('scroll',event=>{if(event.target.classList?.contains('gallery-slider'))update(event.target)},true);
 window.addEventListener('resize',()=>document.querySelectorAll('.gallery-slider').forEach(update));
 document.addEventListener('keydown',event=>{const rail=event.target.closest('.gallery-slider');if(!rail||rail.closest('.card[draggable]')||!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();if(event.key==='Home'||event.key==='End')rail.scrollTo({left:event.key==='Home'?0:rail.scrollWidth,behavior:'instant'});else moveRail(rail,event.key==='ArrowLeft'?-1:1)});
 document.addEventListener('click',event=>{const step=event.target.closest('[data-gallery-step]');if(step){moveRail(step.closest('.card').querySelector('.gallery-slider'),Number(step.dataset.galleryStep));return}const button=event.target.closest('[data-gallery-open]');if(!button)return;const photos=[...button.closest('.gallery-photos').querySelectorAll('img')];let index=Number(button.dataset.galleryOpen);const dialog=document.createElement('dialog');dialog.className='gallery-lightbox';dialog.setAttribute('aria-label','Photo viewer');dialog.innerHTML='<button class="lightbox-close" aria-label="Close photo viewer"><svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button><img alt=""><p></p><div><button class="lightbox-prev" aria-label="Previous photo"><svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 12H4m6-6-6 6 6 6"/></svg></button><span></span><button class="lightbox-next" aria-label="Next photo"><svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 12h16m-6-6 6 6-6 6"/></svg></button></div>';const show=()=>{dialog.querySelector('img').src=photos[index].src;dialog.querySelector('img').alt=photos[index].alt;dialog.querySelector('p').textContent=photos[index].alt;dialog.querySelector('span').textContent=`${index+1} / ${photos.length}`};const move=n=>{index=(index+n+photos.length)%photos.length;show()};dialog.querySelector('.lightbox-prev').onclick=()=>move(-1);dialog.querySelector('.lightbox-next').onclick=()=>move(1);dialog.querySelector('.lightbox-close').onclick=()=>dialog.close();dialog.onkeydown=e=>{if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}};dialog.onclose=()=>{dialog.remove();button.focus()};document.body.append(dialog);show();dialog.showModal();});}
