const preset=(id,name,hint,category,type='link',popular=false,iconName='')=>({id,name,hint,category,type,popular,iconName});
export const linkTypes=[
 preset('website','Website','https://your-site.com','work','link',true),
 preset('portfolio','Portfolio','https://your-portfolio.com','work','project',true,'project'),
 preset('instagram','Instagram','https://www.instagram.com/yourname','social','link',true),
 preset('facebook','Facebook','https://www.facebook.com/yourname','social','link',true),
 preset('tiktok','TikTok','https://www.tiktok.com/@yourname','social','link',true),
 preset('linkedin','LinkedIn','https://www.linkedin.com/in/yourname','social','link',true),
 preset('github','GitHub','https://github.com/yourname','work','link',true),
 preset('youtube','YouTube','https://www.youtube.com/watch?v=VIDEO_ID','media','video',true),
 preset('spotify','Spotify','https://open.spotify.com/artist/your-id','media','link',true),
 preset('whatsapp','WhatsApp','https://wa.me/38640123456','contact','link',true),
 preset('booking','Booking','https://calendly.com/yourname','work','link',true,'calendar'),
 preset('email','Email','hello@example.com','contact','contact',true),
 preset('x','X / Twitter','https://x.com/yourname','social'),
 preset('threads','Threads','https://www.threads.net/@yourname','social'),
 preset('bluesky','Bluesky','https://bsky.app/profile/yourname.bsky.social','social'),
 preset('mastodon','Mastodon','https://mastodon.social/@yourname','social'),
 preset('pinterest','Pinterest','https://www.pinterest.com/yourname','social'),
 preset('snapchat','Snapchat','https://www.snapchat.com/add/yourname','social'),
 preset('reddit','Reddit','https://www.reddit.com/user/yourname','social'),
 preset('discord','Discord','https://discord.gg/yourinvite','social'),
 preset('telegram','Telegram','https://t.me/yourname','contact'),
 preset('gitlab','GitLab','https://gitlab.com/yourname','work'),
 preset('behance','Behance','https://www.behance.net/yourname','work'),
 preset('dribbble','Dribbble','https://dribbble.com/yourname','work'),
 preset('blog','Blog','https://your-site.com/blog','work','link',false,'document'),
 preset('medium','Medium','https://medium.com/@yourname','work','link',false,'document'),
 preset('resume','CV / résumé','https://your-site.com/cv.pdf','work','link',false,'document'),
 preset('newsletter','Newsletter','https://your-site.com/newsletter','work','link',false,'document'),
 preset('substack','Substack','https://yourname.substack.com','work','link',false,'document'),
 preset('shop','Online shop','https://your-shop.com','support','link',false,'catalog'),
 preset('etsy','Etsy','https://www.etsy.com/shop/yourshop','support','link',false,'catalog'),
 preset('gumroad','Gumroad','https://yourname.gumroad.com','support','link',false,'catalog'),
 preset('vimeo','Vimeo','https://vimeo.com/123456789','media','video'),
 preset('twitch','Twitch','https://www.twitch.tv/yourname','media'),
 preset('applemusic','Apple Music','https://music.apple.com/artist/yourname','media','link',false,'audio'),
 preset('soundcloud','SoundCloud','https://soundcloud.com/yourname','media','link',false,'audio'),
 preset('bandcamp','Bandcamp','https://yourname.bandcamp.com','media','link',false,'audio'),
 preset('podcast','Podcast','https://your-site.com/podcast','media','link',false,'audio'),
 preset('video','Other video','https://your-site.com/video','media','video'),
 preset('patreon','Patreon','https://www.patreon.com/yourname','support','link',false,'heart'),
 preset('kofi','Ko-fi','https://ko-fi.com/yourname','support','link',false,'heart'),
 preset('buymeacoffee','Buy Me a Coffee','https://www.buymeacoffee.com/yourname','support','link',false,'heart'),
 preset('paypal','PayPal.Me','https://paypal.me/yourname','support','link',false,'heart'),
 preset('maps','Google Maps','https://www.google.com/maps/search/?api=1&query=your+place','contact','link',false,'location')
];
export const linkCategories=[['popular','Popular'],['social','Social'],['work','Work'],['media','Media'],['support','Support'],['contact','Contact']];
