import {icon,platformIcon} from './icons.js';
import {linkTypes,linkCategories} from './link-presets.js';
export {linkTypes} from './link-presets.js';

export function normalizeLink(raw,kind){const value=raw.trim();if(kind==='email'){const address=value.replace(/^mailto:/i,'');if(!/^[^\s@<>?]+@[^\s@<>?]+\.[^\s@<>?]+$/.test(address))throw Error('Enter a valid email address.');return 'mailto:'+address;}
 if(!value)throw Error('Enter a destination for your link.');
 if(/^[a-z][a-z0-9+.-]*:/i.test(value)&&!/^https?:\/\//i.test(value))throw Error('Use an https:// or http:// address.');
 let url;try{url=new URL(/^https?:\/\//i.test(value)?value:'https://'+value)}catch{throw Error('Enter a valid website address.')}
 if(!url.hostname.includes('.')||url.username||url.password)throw Error('Enter a full website address without login details.');return url.href;
}

export function openLinks(add){
 const dialog=document.createElement('dialog');dialog.className='account-dialog link-dialog';dialog.setAttribute('aria-label','Add a link');
 let chosen=linkTypes[0],category='popular';
 const choices=linkTypes.map(t=>`<button type="button" data-link-kind="${t.id}" aria-pressed="${t===chosen}">${t.iconName?icon(t.iconName):platformIcon(t.id==='email'?'mailto:hello@example.com':t.hint)}<span>${t.name}</span></button>`).join('');
 dialog.innerHTML=`<button class="account-close" aria-label="Close links">${icon('close')}</button><h2>Connect your world.</h2><p>Choose a destination, then add your link.</p><div class="link-toolbar"><label for="link-search">Find a platform<input id="link-search" type="search" placeholder="Search ${linkTypes.length} suggestions" autocomplete="off"></label><div class="link-categories" aria-label="Link categories">${linkCategories.map(([id,label])=>`<button type="button" data-link-category="${id}" aria-pressed="${id===category}">${label}</button>`).join('')}</div></div><div class="link-choices" id="link-choices">${choices}</div><p class="link-count" aria-live="polite"></p><p class="link-empty" hidden>No matches. Clear search to choose Website and paste any link.</p><form><p class="link-selected">Selected: <strong>Website</strong></p><label>Card title<input name="title" maxlength="100" required value="Website"></label><label id="destination-label">Destination<input name="destination" required placeholder="https://your-site.com" autocomplete="off"></label><label>Short description <span class="hint">(optional)</span><input name="description" maxlength="300" placeholder="What will people find here?"></label><label>Appearance<select name="appearance"><option value="card">Classic card</option><option value="icon">Compact icon</option><option value="wide">Wide link</option></select></label><p class="hint">Opens the destination directly. No account connection required.</p><button class="primary" type="submit">Add to my page ${icon('arrow')}</button><p role="status"></p></form>`;
 document.body.append(dialog);dialog.showModal();dialog.querySelector('.account-close').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
 const form=dialog.querySelector('form'),search=dialog.querySelector('#link-search'),buttons=[...dialog.querySelectorAll('[data-link-kind]')];
 const showChoices=()=>{const term=search.value.trim().toLocaleLowerCase();let visible=0;for(const button of buttons){const type=linkTypes.find(t=>t.id===button.dataset.linkKind);button.hidden=!(term?`${type.name} ${type.id} ${type.category}`.toLocaleLowerCase().includes(term):category==='popular'?type.popular:type.category===category);if(!button.hidden)visible++}dialog.querySelector('.link-empty').hidden=visible>0;dialog.querySelector('.link-count').textContent=visible?`${visible} ${term?'matches':'suggestions'}${dialog.querySelector('.link-choices').scrollHeight>dialog.querySelector('.link-choices').clientHeight?' · Scroll for more':''}`:''};
 search.oninput=()=>{dialog.querySelectorAll('[data-link-category]').forEach(item=>item.setAttribute('aria-pressed',String(!search.value.trim()&&item.dataset.linkCategory===category)));showChoices()};
 dialog.querySelectorAll('[data-link-category]').forEach(button=>button.onclick=()=>{category=button.dataset.linkCategory;search.value='';dialog.querySelectorAll('[data-link-category]').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));showChoices()});
 buttons.forEach(button=>button.onclick=()=>{const previous=chosen;chosen=linkTypes.find(t=>t.id===button.dataset.linkKind);if(form.elements.title.value===previous.name)form.elements.title.value=chosen.name;form.elements.destination.value='';form.elements.destination.placeholder=chosen.hint;form.elements.destination.type=chosen.id==='email'?'email':'text';form.elements.appearance.closest('label').hidden=chosen.type!=='link';dialog.querySelector('.link-selected strong').textContent=chosen.name;dialog.querySelector('[role=status]').textContent='';buttons.forEach(item=>item.setAttribute('aria-pressed',String(item===button)));form.elements.destination.focus();form.elements.destination.scrollIntoView({block:'center'})});
 form.onsubmit=event=>{event.preventDefault();try{const url=normalizeLink(form.elements.destination.value,chosen.id);add({id:crypto.randomUUID(),type:chosen.type,size:chosen.type==='project'||chosen.type==='video'||(chosen.type==='link'&&form.elements.appearance.value==='wide')?'wide':'small',linkStyle:form.elements.appearance.value,title:form.elements.title.value.trim()||chosen.name,body:form.elements.description.value.trim(),url});dialog.close()}catch(error){dialog.querySelector('[role=status]').textContent=error.message}};
 showChoices();
}
