export function mapEmbedSource(raw){
 const value=String(raw||'').trim();const src=(value.match(/<iframe\b[^>]*\bsrc\s*=\s*["']([^"']+)["']/i)?.[1]||value).replaceAll('&amp;','&');
 try{const u=new URL(src);if(u.protocol!=='https:'||u.username||u.password)return '';
  if(['www.google.com','maps.google.com'].includes(u.hostname)&&u.pathname==='/maps/embed'&&u.searchParams.has('pb'))return u.href;
  if(u.hostname==='www.google.com'&&u.pathname==='/maps/embed/v1/place'&&u.searchParams.has('key')&&u.searchParams.has('q'))return u.href;
  if(u.hostname==='www.openstreetmap.org'&&u.pathname==='/export/embed.html'&&u.searchParams.has('bbox'))return u.href;
 }catch{}return '';
}
export function addressEmbed(address,key=import.meta.env?.VITE_GOOGLE_MAPS_EMBED_KEY){return address?.trim()&&key?'https://www.google.com/maps/embed/v1/place?'+new URLSearchParams({key,q:address.trim()}):''}
export function mapSettings(c,esc){return `<section class="map-settings"><label>Address<input id="location-address" value="${esc(c.address||'')}" placeholder="Street, city, country"></label><a class="map-search" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(c.address||'')}" target="_blank" rel="noopener noreferrer">Find on Google Maps ↗</a><label>Map display<select id="map-mode"><option value="auto" ${c.mapMode!=='click'&&c.mapMode!=='link'?'selected':''}>Show embedded map</option><option value="click" ${c.mapMode==='click'?'selected':''}>Load on click</option><option value="link" ${c.mapMode==='link'?'selected':''}>Navigation link only</option></select></label><label>Embed map<input id="map-embed" value="${esc(c.mapEmbed||'')}" placeholder="Paste map embed code or URL"></label><p class="hint">In Google Maps choose Share → Embed a map → Copy HTML, then paste it here.${addressEmbed(c.address)?' The address also works automatically.':''}</p><p id="map-status" class="hint" role="status">${!addressEmbed(c.address)&&!c.mapEmbed&&!c.latitude?'Paste an embed code to show the map without coordinates.':''}</p><details class="map-advanced" ${c.latitude!==''&&c.latitude!=null?'open':''}><summary>Advanced: coordinates</summary><label>Latitude<input id="location-latitude" type="number" min="-85" max="85" step="any" value="${esc(c.latitude??'')}"></label><label>Longitude<input id="location-longitude" type="number" min="-180" max="180" step="any" value="${esc(c.longitude??'')}"></label><p class="hint">Coordinates use OpenStreetMap. Editing the address clears the previous map location.</p></details></section>`}
export function bindMaps(card,change){
 document.querySelector('#map-mode')?.addEventListener('change',e=>change(()=>card.mapMode=e.target.value));
 document.querySelector('#map-embed')?.addEventListener('change',e=>{const raw=e.target.value,src=mapEmbedSource(raw);if(raw.trim()&&!src){document.querySelector('#map-status').textContent='Paste the Embed a map code, not a regular sharing link. Supported: Google Maps and OpenStreetMap.';return}change(()=>{card.mapEmbed=src;card.latitude='';card.longitude=''})});
}
