import {cleanProfile,languages,makeVCard} from './profile-data.js';
import {cloud} from './cloud.js';
const words={en:{contact:'Contact me',name:'Name',email:'Email',message:'Message',send:'Send message',save:'Save contact',sent:'Message sent. Thank you!',preview:'Available on your published page.',privacy:'Your name, email and message will be shared with this profile’s owner.'},sl:{contact:'Piši mi',name:'Ime',email:'E-pošta',message:'Sporočilo',send:'Pošlji sporočilo',save:'Shrani kontakt',sent:'Sporočilo je poslano. Hvala!',preview:'Na voljo na objavljeni strani.',privacy:'Tvoje ime, e-pošta in sporočilo bodo posredovani lastniku tega profila.'}};
export function profileExtras(page,esc,language){const p=cleanProfile(page.profile),codes=[...new Set([p.defaultLanguage,...p.languages])],t=words[language]||words.en;return `${codes.length>1?`<label class="public-language">Language / Jezik<select data-profile-language>${codes.map(code=>`<option value="${code}" ${code===language?'selected':''}>${languages[code]}</option>`).join('')}</select></label>`:''}${p.vcard.enabled?`<a class="vcard-download" download="contact.vcf" href="data:text/vcard;charset=utf-8,${esc(encodeURIComponent(makeVCard({...p.vcard,name:p.vcard.name||page.name})))}">${t.save} ↓</a>`:''}${p.contactForm?`<section class="public-contact"><h2>${t.contact}</h2><form data-contact-form><label>${t.name}<input name="name" required maxlength="100" autocomplete="name"></label><label>${t.email}<input name="email" type="email" required maxlength="254" autocomplete="email"></label><label>${t.message}<textarea name="message" required maxlength="5000" rows="4"></textarea></label><div class="form-trap" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="hint">${t.privacy}</p><button type="submit">${t.send}</button><p role="status"></p></form></section>`:''}`}
export function bindPublicProfile(page,{slug='',language='en',changeLanguage,trackView=true}){
 const root=document.querySelector('.personal-page');if(!root)return;const t=words[language]||words.en;
 root.querySelector('[data-profile-language]')?.addEventListener('change',event=>changeLanguage(event.target.value));
 const form=root.querySelector('[data-contact-form]');if(form)form.onsubmit=async event=>{event.preventDefault();const status=form.querySelector('[role=status]');if(!slug){status.textContent=t.preview;return}const button=form.querySelector('button');button.disabled=true;status.textContent='…';try{const values=Object.fromEntries(new FormData(form));const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,slug}),signal:AbortSignal.timeout(20000)});if(!response.headers.get('content-type')?.includes('application/json'))throw Error('Contact service is not available yet.');const result=await response.json();if(!response.ok)throw Error(result.error||'Could not send your message.');form.reset();status.textContent=t.sent}catch(error){status.textContent=error.message}finally{button.disabled=false}};
 if(!slug||!page.profile?.analytics||navigator.doNotTrack==='1'||navigator.globalPrivacyControl)return;
 const record=async(event,card='')=>{try{const session=cloud?(await cloud.auth.getSession()).data.session:null;await fetch('/api/event',{method:'POST',headers:{'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session.access_token}:{})},body:JSON.stringify({slug,event,card}),keepalive:true})}catch{}};
 if(trackView)record('view');root.addEventListener('click',event=>{const link=event.target.closest('a,[data-video-load],[data-map-load]');const card=link?.closest('[data-id]');if(card)record('click',card.dataset.id)});
}
