import {galleryRuntime} from './gallery.js';
import {mediaRuntime} from './media.js';
import {businessCard} from './business-card.js';
import {bentoRuntime} from './bento-layout.js';
import {icon} from './icons.js';
import {sampleProfiles} from './sample-profiles.js';
import {defaults,styleString} from './design.js';
const photo=(id,title,image,size='small')=>({id,type:'photo',size,title,body:'',image});
const block=(id,type,size,title,body,url)=>({id,type,size,title,body,...(url?{url}:{})});
export const templates=[
 {id:'creator',label:'Creator',subtitle:'A bold home for your latest work.',tag:'CREATE & SHARE',name:'Alex Rivera',accent:'#ad8cff',gap:16,radius:18,design:{...defaults,background:'#14111c',surface:'#211b2d',border:'#3b304b',text:'#f5f0ff',muted:'#bfb1d1',headingFont:'grotesk',weight:600},cards:[block('c-intro','intro','wide','Ideas into things.','I’m Alex. I make films, share ideas, and follow my curiosity.','mailto:hello@example.com'),photo('c-photo','Behind the scenes','https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=700&auto=format&fit=crop'),block('c-video','video','wide','Watch my latest film','A new perspective, one frame at a time.','https://www.youtube.com/'),block('c-now','text','small','On the drawing board','A short film. A new series. Something unexpected.'),block('c-project','project','wide','The creative journal','Experiments, sketches, and the work in between.','https://example.com'),block('c-social','link','small','Find me on Instagram','More of the everyday.','https://instagram.com')]},
 {id:'professional',label:'Professional',subtitle:'Make your experience stand out.',tag:'WORK & CONNECT',name:'Jordan Lee',accent:'#2563eb',gap:16,radius:8,design:{...defaults,mode:'light',background:'#eef2f7',surface:'#ffffff',border:'#d5deeb',text:'#19283d',muted:'#53647b',headingFont:'sans',weight:600,shadow:'soft'},cards:[block('p-intro','intro','wide','Thoughtful design. Real impact.','Jordan Lee — independent designer helping teams turn complex ideas into simple experiences.','mailto:jordan@example.com'),block('p-contact','contact','small','Let’s work together','Available for selected projects and collaborations.','mailto:jordan@example.com'),block('p-project','project','wide','Selected case study','From an early idea to a product people love using.','https://example.com'),block('p-services','text','tall','How I can help','Product design\nDesign systems\nCreative direction\nStrategy & discovery'),block('p-experience','text','wide','Experience that connects the dots','An independent practice built around clarity, collaboration, and care.'),block('p-link','link','small','LinkedIn','Experience & connections','https://linkedin.com')]},
 {id:'personal',label:'Personal',subtitle:'A little corner that feels like you.',tag:'LIFE & INTERESTS',name:'Sam Taylor',accent:'#39745c',gap:20,radius:24,design:{...defaults,mode:'light',background:'#f1f3eb',surface:'#fcfdf7',border:'#d8dfd0',text:'#293b31',muted:'#617061',headingFont:'serif',weight:400,buttonRadius:24},cards:[block('s-intro','intro','wide','A little about me.','I’m Sam. A curious person collecting places, stories, and small moments.','mailto:sam@example.com'),photo('s-portrait','Hello from Sam','https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=700&auto=format&fit=crop'),photo('s-photo','Somewhere I feel at home','https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1100&auto=format&fit=crop','wide'),block('s-now','text','small','These days','Reading more. Learning to cook. Taking the scenic route.'),block('s-interests','text','wide','Things that make me happy','Long walks, good coffee, old bookstores, and a camera in my backpack.'),block('s-contact','contact','small','Say hello','Always happy to meet a fellow curious human.','mailto:sam@example.com')]}
];
templates.push(...sampleProfiles,businessCard);
export function openTemplates(state,pageHTML,apply){
 const dialog=document.createElement('dialog');dialog.className='template-dialog';let chosen=templates[0];
 dialog.innerHTML=`<div class="template-header"><div><span class="eyebrow">A PLACE TO START</span><h2>Find your starting point.</h2><p>Personal pages, portfolios, and a digital business card.</p></div><button class="template-close" aria-label="Close templates">${icon('close')}</button></div><div class="template-body"><div class="template-list">${templates.map((t,i)=>`<button data-template="${t.id}" aria-pressed="${i===0}"><div class="template-thumbnail" aria-hidden="true"><iframe class="template-thumb-frame" data-thumb="${t.id}" title="${t.label} thumbnail" tabindex="-1" inert sandbox="allow-scripts"></iframe></div><span class="eyebrow">${t.tag}</span><strong>${t.label}</strong><small>${t.subtitle}</small></button>`).join('')}</div><div class="template-preview"><div class="template-preview-label">LIVE TEMPLATE PREVIEW <span id="template-label">Creator</span></div><iframe title="Template preview" sandbox="allow-scripts" srcdoc=""></iframe></div></div><div class="template-footer"><label><input id="keep-content" type="checkbox" checked> Keep my existing content <small>Apply this style and layout to your cards.</small></label><button class="primary" id="apply-template">Use Creator template ↗</button><p id="template-error" role="status"></p></div>`;
 document.body.append(dialog);dialog.showModal();dialog.querySelector('.template-close').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
 let css='';const show=()=>{const frame=dialog.querySelector('iframe[title="Template preview"]');frame.srcdoc=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body class="export-page" style="${styleString(chosen).replaceAll('"','&quot;')}">${pageHTML(false,chosen)}<script>(${bentoRuntime.toString()})();(${mediaRuntime.toString()})();(${galleryRuntime.toString()})();</script></body></html>`;dialog.querySelector('#template-label').textContent=chosen.label;dialog.querySelector('#apply-template').textContent=`Use ${chosen.label} template ↗`;dialog.querySelectorAll('[data-template]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.template===chosen.id)))};
 import('./style.css?inline').then(module=>{css=module.default;dialog.querySelectorAll('[data-thumb]').forEach(frame=>{const template=templates.find(t=>t.id===frame.dataset.thumb);frame.srcdoc=`<!doctype html><html><head><style>${css}html,body{overflow:hidden}.export-page{width:800px;margin:0}.page-nav{height:64px}</style></head><body class="export-page" style="${styleString(template).replaceAll('"','&quot;')}">${pageHTML(false,template)}<script>(${bentoRuntime.toString()})();(${mediaRuntime.toString()})();(${galleryRuntime.toString()})();</script></body></html>`});show()});
 dialog.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{chosen=templates.find(t=>t.id===b.dataset.template);show()});
 dialog.querySelector('#keep-content').onchange=e=>{e.target.nextElementSibling.textContent=e.target.checked?'Apply this style and layout to your cards.':'Replaces your cards with sample content. Undo restores your page.'};
 dialog.querySelector('#apply-template').onclick=()=>{try{apply(chosen,dialog.querySelector('#keep-content').checked);dialog.close()}catch(e){dialog.querySelector('#template-error').textContent=e.message}};
}
