import {templates} from './templates.js';
import {preparePhoto} from './photos.js';
import {normalizeLink} from './links.js';
import {cleanPage} from './page-data.js';
import {icon} from './icons.js';

const purposes=[['personal','Personal page','Your interests, story and favourite links.'],['portfolio','Portfolio','Introduce your work and connect with clients.'],['business','Business card','A clear introduction and ways to reach you.']];
const styles={personal:['personal','creator'],portfolio:['professional','creator'],business:['business-card','professional']};
export function welcomeDocument({purpose,templateId,name,bio,image,links}){
 const template=templates.find(t=>t.id===templateId&&styles[purpose]?.includes(t.id));
 if(!template||!name.trim())throw Error('Choose a template and enter your name.');
 const cards=[{id:'welcome-intro',type:'intro',size:'wide',title:name.trim(),body:bio.trim()}];
 if(image)cards.push({id:'welcome-photo',type:'photo',size:'small',title:name.trim(),alt:'Portrait of '+name.trim(),image,photoRole:'portrait'});
 for(const link of links){if(!link.url.trim())continue;const url=normalizeLink(link.url,/^mailto:/i.test(link.url)?'email':'website');cards.push({id:'welcome-link-'+cards.length,type:url.startsWith('mailto:')?'contact':'link',size:'small',title:link.title.trim()||(url.startsWith('mailto:')?'Email':new URL(url).hostname),url,body:''})}
 return cleanPage({...template,name:name.trim(),cards,onboarding:{name:true,photo:!!image,link:cards.some(c=>c.url)}});
}
export function openWelcome({complete,skip,signIn}){
 let step=0,purpose='personal',templateId='personal',photo='',photoVersion=0,busy=false;
 const dialog=document.createElement('dialog');dialog.className='account-dialog welcome-dialog';dialog.setAttribute('aria-labelledby','welcome-heading');
 dialog.innerHTML=`<span class="eyebrow">WELCOME TO VERBASPARK</span><h2 id="welcome-heading">A page that feels like you.</h2><p id="welcome-progress" aria-live="polite"></p><form id="welcome-form"><section data-welcome-step="0"><h3>What would you like to create?</h3><div class="welcome-choices">${purposes.map(([id,label,description])=>`<button type="button" data-purpose="${id}" aria-pressed="${id===purpose}"><strong>${label}</strong><small>${description}</small></button>`).join('')}</div></section><section data-welcome-step="1" hidden><h3>Choose your starting style</h3><p>You can customize every colour, font and card later.</p><div id="welcome-templates" class="welcome-choices"></div></section><section data-welcome-step="2" hidden><h3>Make it yours</h3><label>Your name<input id="welcome-name" maxlength="100" autocomplete="name" required></label><label>A short introduction <small>Optional</small><textarea id="welcome-bio" rows="2" maxlength="1000" placeholder="What would you like people to know about you?"></textarea></label><label>Profile photo <small>Optional · JPG, PNG or WebP · up to 15 MB</small><input id="welcome-photo" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="welcome-photo-preview" hidden><img alt="Your profile photo" width="64" height="64"><button id="welcome-remove-photo" type="button">Remove photo</button></div><p id="welcome-photo-status" aria-live="polite"></p><fieldset><legend>Your first links <small>Optional</small></legend>${[0,1,2].map(i=>`<div class="welcome-link"><label>Link ${i+1} name<input data-welcome-title="${i}" maxlength="100" placeholder="${['My website','Instagram','Email'][i]}"></label><label>Destination<input data-welcome-url="${i}" maxlength="2000" placeholder="${i===2?'mailto:hello@example.com':'https://…'}"></label></div>`).join('')}</fieldset><p class="hint">This creates a private draft. You decide when to publish.</p></section><p id="welcome-error" role="alert"></p><div class="welcome-navigation"><button type="button" id="welcome-back">Back</button><button type="submit" id="welcome-next" class="primary">Continue ${icon('right')}</button></div></form><div class="welcome-footer"><button id="welcome-skip">Skip to editor</button><button id="welcome-signin">Already have a page? Sign in</button></div>`;
 document.body.append(dialog);dialog.showModal();const find=s=>dialog.querySelector(s);
 const leave=fn=>{photoVersion++;dialog.close();fn()};dialog.onclose=()=>dialog.remove();dialog.oncancel=e=>{e.preventDefault();leave(skip)};
 find('#welcome-skip').onclick=()=>leave(skip);find('#welcome-signin').onclick=()=>leave(signIn);
 const show=()=>{dialog.querySelectorAll('[data-welcome-step]').forEach(el=>el.hidden=Number(el.dataset.welcomeStep)!==step);find('#welcome-name').required=step===2;find('#welcome-progress').textContent=`Step ${step+1} of 3 · ${['Purpose','Style','Your details'][step]}`;find('#welcome-back').hidden=step===0;find('#welcome-next').textContent=step===2?'Create my page':'Continue →';find('#welcome-error').textContent='';if(step===2)find('#welcome-name').focus();else find(`[data-welcome-step="${step}"] button`)?.focus();dialog.scrollTop=0};
 const showStyles=()=>{const list=find('#welcome-templates');list.replaceChildren();for(const id of styles[purpose]){const t=templates.find(t=>t.id===id);const button=document.createElement('button');button.type='button';button.dataset.welcomeTemplate=id;button.setAttribute('aria-pressed',String(id===templateId));const preview=document.createElement('div');preview.className='welcome-style-preview '+(t.layout==='classic'?'classic':'bento');preview.setAttribute('aria-hidden','true');preview.style.background=t.design.background;for(let i=0;i<4;i++){const block=document.createElement('span');block.style.background=i===0?t.accent:t.design.surface;block.style.borderColor=t.design.border;block.style.borderRadius=t.radius+'px';preview.append(block)}const label=document.createElement('strong');label.textContent=t.label;const detail=document.createElement('small');detail.textContent=t.layout==='classic'?'A clean, vertical profile':'A flexible bento layout';button.append(preview,label,detail);button.onclick=()=>{templateId=id;list.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)))};list.append(button)}};
 dialog.querySelectorAll('[data-purpose]').forEach(button=>button.onclick=()=>{purpose=button.dataset.purpose;templateId=styles[purpose][0];dialog.querySelectorAll('[data-purpose]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));showStyles()});
 find('#welcome-back').onclick=()=>{step--;show()};
 find('#welcome-photo').onchange=async e=>{const file=e.target.files[0];if(!file)return;const version=++photoVersion;busy=true;find('#welcome-next').disabled=true;find('#welcome-photo-status').textContent='Preparing photo…';try{const result=await preparePhoto(file);if(version!==photoVersion||!dialog.isConnected)return;photo=result;find('.welcome-photo-preview img').src=photo;find('.welcome-photo-preview').hidden=false;find('#welcome-photo-status').textContent='Photo ready.'}catch(error){if(version===photoVersion)find('#welcome-photo-status').textContent=error.message}finally{if(version===photoVersion){busy=false;find('#welcome-next').disabled=false}}};
 find('#welcome-remove-photo').onclick=()=>{photoVersion++;photo='';busy=false;find('#welcome-next').disabled=false;find('#welcome-photo').value='';find('.welcome-photo-preview').hidden=true;find('#welcome-photo-status').textContent=''};
 find('#welcome-form').onsubmit=e=>{e.preventDefault();if(step<2){step++;show();return}if(busy)return;try{const result=welcomeDocument({purpose,templateId,name:find('#welcome-name').value,bio:find('#welcome-bio').value,image:photo,links:[0,1,2].map(i=>({title:find(`[data-welcome-title="${i}"]`).value,url:find(`[data-welcome-url="${i}"]`).value}))});complete(result);dialog.close()}catch(error){find('#welcome-error').textContent=error.message}};
 showStyles();show();
}
